services:
  chatapp:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: production
      FLASK_APP: minimal_webserver.py
    command: ["python", "minimal_webserver.py"]